#!/bin/sh
# lowerit
# convert all file names in the current directory to lower case
# only operates on plain files--does not change the name of directories
# will ask for verification before overwriting an existing file
for x in `ls`
  do
  if [ ! -f $x ]; then
  continue
  fi
echo -e "$x \n"	
   cat $x  | tr '[a-z]' '[a-z]' > temp
sleep 1
   cat temp > $x

done
